name: Ubuntu package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
                sudo apt-get update
                sudo apt-get install clang ninja-build python3-pip python3-setuptools \
                libsdl2-dev libpng-dev libepoxy-dev libopenal-dev libgtk-3-dev
      - name: Install meson
                pip3 install wheel
                pip3 install meson
      - name: Install scdoc
        run: |
                git clone https://git.sr.ht/~sircmpwn/scdoc --depth 1
                cd scdoc
                make
                sudo make install
      - name: Meson build
        run: CC=clang LDSHARED="clang -shared" ~/.local/bin/meson build
      - name: Ninja
        run: ninja -C build
